local neaterm = {
  "Dan7h3x/neaterm.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "ibhagwan/fzf-lua",
  },
  branch = "stable",
  event = "VeryLazy",
  opts = {
    keymaps = {
      toggle = "<C-n>tt",
      new_vertical = "<C-n>tv",
      new_horizontal = "<C-n>th",
      new_float = "<C-n>tf",
      close = "<C-n>q",
      next = "<C-n>.",
      prev = "<C-n>,",
      move_up = "<C-n>k",
      move_down = "<C-n>j",
      move_left = "<C-n>h",
      move_right = "<C-n>l",
      resize_up = "<C-n>K",
      resize_down = "<C-n>J",
      resize_left = "<C-n>H",
      resize_right = "<C-n>L",
      focus_bar = "<C-n>b",
      repl_toggle = "<C-n>rt",
      repl_send_line = "<C-n>rl",
      repl_send_selection = "<C-n>rs",
      repl_send_buffer = "<C-n>rb",
      repl_clear = "<C-n>rc",
      repl_history = "<C-n>rh",
      repl_variables = "<C-n>rv",
      repl_restart = "<C-n>rr",
    },
    repl_configs = {
      python = {
        name = "Python",
        cmd = "python",
        startup_cmds = {},
        get_variables_cmd = "whos",
        inspect_variable_cmd = "?",
        exit_cmd = "exit()",
      },
      lua = {
        name = "Lua",
        cmd = "lua",
        exit_cmd = "os.exit()",
      },
      swift = {
        name = "Swift",
        cmd = "swift repl",
        get_variables_cmd = "po",
        inspect_variable_cmd = "po",
        exit_cmd = ":exit",
      },
    },
  },
}

return neaterm
