# alacritty.toml

[window]
decorations = "buttonless"
opacity = 0.7
title = ""

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style  = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style  = "Regular"

# Gruvbox-Material colors
# Default colors
[colors.primary]
background = '#1b1b1b'
foreground = '#ddc7a1'

[colors.cursor]
cursor = '#ea6962'
text = '#15161e'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#e78a4e'

# Bright colors
[colors.bright]
black = '#15161e'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#e78a4e'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ddc7a1'

[[colors.indexed_colors]]
index = 17
color = '#ea6962'
