# alacritty.toml

[window]
decorations = "buttonless"
opacity = 0.9
title = ""

[font]
size = 12.0

[font.bold]
family = "Source Code Pro"
style  = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style  = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style  = "Italic"

[font.normal]
family = "Source Code Pro"
style  = "Regular"
