#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor DP-4 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         3
bspc config active_border_color \#444444
bspc config focused_border_color \#5500DD
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a alacritty desktop=^1 -o
bspc rule -a jetbrains-studio desktop=^2 -o
bspc rule -a Slack desktop=^3 -o
bspc rule -a discord desktop=^4 -o
bspc rule -a firefox desktop=^6 -o

alacritty &
firefox &
discord &
