# Taps
tap 'homebrew/core'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'
tap 'romkatv/powerlevel10k'

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# Install GNU core utilities (those that come with OS X are outdated)
brew 'coreutils'

# Install Binaries
brew 'git'
brew 'neovim'
brew 'fzf'
brew 'romkatv/powerlevel10k/powerlevel10k'

# Install Casks
cask 'iterm2'
cask 'proxyman'
cask 'stats'

# Install Fonts
cask 'font-meslo-lg-nerd-font'
