#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         5
bspc config active_border_color \#d8a657
bspc config focused_border_color \#ea6962
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
