#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         8
bspc config normal_border_color \#d8a657
bspc config focused_border_color \#ea6962
bspc config window_gap          12
bspc config top_padding 30
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
